#!/usr/bin/env python3
"""Generate tests/roblox_api.lua (class -> parent + member names) from the Roblox API type definitions.

The test harness uses it to behave like real Roblox: reading or writing a member that doesn't exist on an
Instance raises "X is not a valid member of Class". Regenerate when the Roblox API changes:
    python3 tools/gen_api.py path/to/globalTypes.d.luau
"""
import os, re, sys
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
defs = open(sys.argv[1], encoding="utf-8").read()
out = ["-- generated by tools/gen_api.py from the Roblox API definitions: class = {parent, {members...}}", "return {"]
n = 0
for m in re.finditer(r"^declare extern type (\w+) extends (\w+) with\n(.*?)^end$", defs, re.S | re.M):
    name, parent, body = m.groups()
    members = set(re.findall(r"^\s+(\w+)\s*:", body, re.M)) | set(re.findall(r"^\s+function (\w+)\(", body, re.M))
    out.append('\t%s = {"%s", {%s}},' % (name, parent, ", ".join('"%s"' % x for x in sorted(members))))
    n += 1
for base in ["Object"]:
    m = re.search(r"^declare extern type %s with\n(.*?)^end$" % base, defs, re.S | re.M)
    if m:
        body = m.group(1)
        members = set(re.findall(r"^\s+(\w+)\s*:", body, re.M)) | set(re.findall(r"^\s+function (\w+)\(", body, re.M))
        out.append('\t%s = {"", {%s}},' % (base, ", ".join('"%s"' % x for x in sorted(members))))
out.append("}")
open(os.path.join(ROOT, "tests", "roblox_api.lua"), "w", encoding="utf-8").write("\n".join(out) + "\n")
print("wrote tests/roblox_api.lua with %d classes" % n)
